### ISSUE TITLE
Security risk: Public client token id and secret key

### ISSUE THREAD

**Issue by t3bol90** [ansoncaonguyen/intro2ds-final-project#2]
I found and client_id and client_secret on your directly commit to Git.

This problem can not be solve using another commit, history commit can be restored.

Reference by this article to know the risk of public key API on Git: https://www.kaspersky.com/blog/tokens-on-github/26238/

Finally, to fix that problem, try to use .gitignore file with config.yaml or .toml file - more over, let try to use .env: a local enviroment setting.

**Comment by ansoncaonguyen** [comment]
Thanks for your useful information, we've updated our project so that there will be none credentials information in `collect_data.ibynb` itself nor the commit history.
