### ISSUE TITLE
Explaination: Better explaination for statement: instrumentalness is alway zero!

### ISSUE THREAD

**Issue by t3bol90** [ansoncaonguyen/intro2ds-final-project#3]
Instrumentalness is the "Predicts whether a track contains no vocals. The closer the instrumentalness value is to 1.0 the greater likelihood the track contains no vocal content". So in Top 100 hits, there are not much tracks with "no vocals" (EDM, Beat, Karaoke version,...). This lead to the continuous uniform distribution of instrumentalness - it's related to your problem. I think you need to have a clearly explain for it.

**Comment by ansoncaonguyen** [comment]
Thank you for your contribution, we've updated it so that it has a clearer explanation.
