### ISSUE TITLE
Improve project: Using Zalo AI Challenge with interesting neural network

### ISSUE THREAD

**Issue by t3bol90** [ansoncaonguyen/intro2ds-final-project#4]
Your problem seem to be like Zalo AI Challenge 2019 problem: Hit Song Prediction.

So I referenced the 2nd solution of this Challenge with better approach:
- https://github.com/vuthede/zalo-hit-song-prediction

Another solution would be considerable:
- https://github.com/anhtholee/zalo-hit-song

**Comment by ansoncaonguyen** [comment]
Thanks for your reference. We will use these solutions effectively to improve our project!

**Comment by t3bol90** [comment]
<3 Good luck with your project presentation
